apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaddem-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kaddem-app
  template:
    metadata:
      labels:
        app: kaddem-app
    spec:
      containers:
      - name: kaddem-app
        image: oussabd/abdellaouioussema-g2-4twin2:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8090
        env:
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:mysql://mysql-service:3306/kaddem?useSSL=false&allowPublicKeyRetrieval=true"
          - name: SPRING_DATASOURCE_USERNAME
            value: "root"
          - name: SPRING_DATASOURCE_PASSWORD
            value: "root"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"