version: "3.8"

services:
  abdellaouioussema-4twin2-g6-kaddem:
    container_name: kaddem-app
    image: abdellaouioussema-g2-4twin2:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8089"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/kaddem?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - TZ=Europe/Paris
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-network

  db:
    container_name: mysql-db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kaddem
      TZ: Europe/Paris
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    container_name: my-prometheus-container
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    networks:
      - app-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - app-network

volumes:
  grafana-storage:

networks:
  app-network:
    driver: bridge
