FROM openjdk:8-jdk-alpine
EXPOSE 8089
ADD http://192.168.33.10:8081/repository/maven-releases/tn/esprit/spring/kaddem/1.0.1/kaddem-1.0.1.jar /kaddem-1.0.1.jar
ENTRYPOINT ["java","-jar","/kaddem-1.0.1.jar"]
