pipeline {
    agent any

    tools {
 jdk 'JAVA_HOME'
        maven 'M2_HOME'    }

    environment {
        SONARQUBE = 'SonarServer'  // Nom défini dans Jenkins > SonarQube servers
        DOCKER_IMAGE = 'nourchenebenabdallah-4twin2-g2-kaddem:latest'
    }

  stages {
        stage('Checkout') {
            steps {
                git branch: 'NourcheneBenAbdallah-4TWIN2-G2', url: 'https://github.com/NourcheneBenAbdallahh/4TWIN2-G2-KADDEM.git'
            }
        }

        stage('Build & Test') {
            steps {
                dir('kaddem/kaddem') {
                    sh 'mvn clean install'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('kaddem/kaddem') {
                    withSonarQubeEnv("${env.SONARQUBE}") {
                        sh 'mvn sonar:sonar'
                    }
                }
            }
        }

        stage('Deploy to Nexus') {
            steps {
                dir('kaddem/kaddem') {
                    sh 'mvn deploy'
                }
            }
        }
      stage('Build Docker Image') {
            steps {
                dir('kaddem/kaddem') {
                    sh 'docker build -t ${DOCKER_IMAGE} .'
                }
            }
        }
        stage('Run Docker Compose') {
            steps {
                dir('kaddem/kaddem') {
      sh 'docker compose up -d --build'
                }
            }
        }
    }

    post {
        success {
            echo '✅ Pipeline terminé avec succès.'
        }
        failure {
            echo '❌ Échec du pipeline.'
        }
    }
}
