pipeline {
    agent any

    tools {
 jdk 'JAVA_HOME'
        maven 'M2_HOME'    }

    environment {
        SONARQUBE = 'SonarServer'  // Nom défini dans Jenkins > SonarQube servers
    DOCKER_IMAGE = 'nourcheneba/kenzo:nourchenebenabdallah-4twin2-g2-kaddem'
            DOCKER_COMPOSE = '/usr/local/bin/docker-compose'

    }

  stages {
        stage('Checkout') {
            steps {
                git branch: 'NourcheneBenAbdallah-4TWIN2-G2', url: 'https://github.com/NourcheneBenAbdallahh/4TWIN2-G2-KADDEM.git'
            }
        }

        stage('Build & Test') {
            steps {
                dir('kaddem/kaddem') {
                    sh 'mvn clean install'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('kaddem/kaddem') {
                    withSonarQubeEnv("${env.SONARQUBE}") {
                        sh 'mvn sonar:sonar'
                    }
                }
            }
        }

        stage('Deploy to Nexus') {
            steps {
                dir('kaddem/kaddem') {
                    sh 'mvn deploy'
                }
            }
        }

       stage('Deploy Prometheus') {
            steps {
                dir('.') {
                    sh "${DOCKER_COMPOSE} up -d prometheus"
                }
            }
        }

      stage('Build Docker Image') {
            steps {
                dir('kaddem/kaddem') {
                    sh 'docker build -t ${DOCKER_IMAGE} .'
                }
            }
        }
        stage('Run Docker Compose') {
            steps {
                dir('kaddem/kaddem') {
                    
      sh 'docker compose up -d --build'
                }
            }
        }

      stage('Push to Docker Hub') {
    steps {
        dir('kaddem/kaddem') {
            script {
                docker.withRegistry('https://index.docker.io/v1/', 'docker-hub-credentials-id') {
                    sh "docker tag ${DOCKER_IMAGE} nourcheneba/kenzo:nourchenebenabdallah-4twin2-g2-kaddem"
                    sh "docker --debug push ${DOCKER_IMAGE}"
                }
            }
        }
    }
}

    }

    post {
        success {
            echo '✅ Pipeline terminé avec succès.'
        }
        failure {
            echo '❌ Échec du pipeline.'
        }
    }
}
